name       : fifengine
version    : 0.4.1
release    : 4
source     :
    - https://github.com/fifengine/fifengine/archive/0.4.1.tar.gz : bae3fc591cc2891f7d1b3a656a5d8ad700ecc2e297ad453bf4f1bcbbf82e8cb2
license    : LGPL-2.1-or-later
component  : programming
summary    : Flexible Isometric Free Engine (FIFE) is a multi-platform isometric game engine written in C++
description: |
    Flexible Isometric Free Engine (FIFE) is a multi-platform isometric game engine written in C++.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(gl)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(tinyxml)
    - pkgconfig(vorbis)
    - pkgconfig(xcursor)
    - fifechan-devel
    - libboost-devel
    - swig
setup      : |
    mkdir _build && cd _build
    %cmake ..
build      : |
    %make -C _build
install    : |
    %make_install -C _build
